from pathlib import Path
p=Path('sceneforge-animate/phase13.html')
s=p.read_text(encoding='utf-8')
s=s.replace('Phase 1.3','Phase 1.4')
s=s.replace('Director → dense multi-view QA → validated Repair JSON','Director → auto-facing runtime → orientation QA → validated Repair JSON')
s=s.replace('每个采样时刻截 3 张：导演视角、左侧视角、右侧视角。若超过图片上限，会均匀抽样时间点，但始终成组三视角。','每个采样时刻截 3 张：导演视角、左侧视角、右侧视角。还会计算角色 forward、移动方向和互动目标的朝向点积。若超过图片上限，会均匀抽样时间点，但始终成组三视角。')
s=s.replace("const ACTIONS=['walk','run','wave','dance','react','jump','idle','pause','face'];", "const ACTIONS=['walk','run','wave','dance','react','jump','idle','pause','face'];\n// RobotExpressive visual front is opposite the +Z convention used by the director DSL.\nconst MODEL_FORWARD_OFFSET={robot:Math.PI,fox:0};")
s=s.replace("function lerp3(a,b,t){return a.map((v,i)=>THREE.MathUtils.lerp(v,b[i],t))}\n", "function lerp3(a,b,t){return a.map((v,i)=>THREE.MathUtils.lerp(v,b[i],t))}\nfunction normAngle(a){while(a>Math.PI)a-=Math.PI*2;while(a<-Math.PI)a+=Math.PI*2;return a}\nfunction angleDelta(a,b){return normAngle(b-a)}\nfunction lerpAngle(a,b,t){return normAngle(a+angleDelta(a,b)*t)}\nfunction yawTo(from,to,type){const dx=to[0]-from[0],dz=to[2]-from[2];if(Math.hypot(dx,dz)<1e-5)return null;return normAngle(Math.atan2(dx,dz)+(MODEL_FORWARD_OFFSET[type]||0))}\nfunction forwardFromYaw(yaw,type){const a=yaw-(MODEL_FORWARD_OFFSET[type]||0);return [Math.sin(a),Math.cos(a)]}\nfunction unit2(x,z){const l=Math.hypot(x,z);return l<1e-6?[0,0]:[x/l,z/l]}\nfunction dot2(a,b){return a[0]*b[0]+a[1]*b[1]}\n")
s=s.replace("      if(!ACTIONS.includes(b?.action))errors.push(`shots[${i}].beats[${j}] action invalid`);\n      if(!Number.isFinite(Number(b?.start))||!Number.isFinite(Number(b?.end)))errors.push(`shots[${i}].beats[${j}] time invalid`);", "      if(!ACTIONS.includes(b?.action))errors.push(`shots[${i}].beats[${j}] action invalid`);\n      if(b?.faceTarget!=null&&!ids.has(String(b.faceTarget)))errors.push(`shots[${i}].beats[${j}] faceTarget invalid`);\n      if(!Number.isFinite(Number(b?.start))||!Number.isFinite(Number(b?.end)))errors.push(`shots[${i}].beats[${j}] time invalid`);")
s=s.replace("      to:Array.isArray(b.to)&&b.to.length===3?[clamp(b.to[0],-10,10),0,clamp(b.to[2],-5,5)]:null,\n      rotationY:Number.isFinite(Number(b.rotationY))?clamp(b.rotationY,-6.3,6.3,0):null", "      to:Array.isArray(b.to)&&b.to.length===3?[clamp(b.to[0],-10,10),0,clamp(b.to[2],-5,5)]:null,\n      faceTarget:b.faceTarget!=null&&ids.has(String(b.faceTarget))?String(b.faceTarget):null,\n      rotationY:Number.isFinite(Number(b.rotationY))?clamp(b.rotationY,-6.3,6.3,0):null")
start=s.index('function compile(){')
end=s.index('\nfunction stateAt',start)
s=s[:start]+r'''function compile(){
  const curs=new Map(plan.assets.map(a=>[a.id,{pos:[...a.position],rot:a.rotationY}])),actions=[];
  const orderedShots=[...plan.shots].sort((a,b)=>a.start-b.start);
  for(const shot of orderedShots){
    let interactionFaced=false;
    const beats=[...shot.beats].sort((a,b)=>a.start-b.start);
    for(const b of beats){
      const spec=plan.assets.find(x=>x.id===b.target),st=curs.get(b.target);if(!spec||!st)continue;
      if(['walk','run'].includes(b.action)){
        const to=b.to||[st.pos[0]+2,0,st.pos[2]],autoYaw=yawTo(st.pos,to,spec.type);
        if(autoYaw!==null){const turnEnd=Math.min(b.end,b.start+.16);actions.push({target:b.target,type:'rotate',start:b.start,end:turnEnd,from:st.rot,to:autoYaw,reason:'auto-face movement'});st.rot=autoYaw}
        actions.push({target:b.target,type:'move',start:b.start,end:b.end,from:[...st.pos],to:[...to],clip:actionClip(spec.type,b.action)});st.pos=[...to];
      }else if(b.action==='face'){
        let targetYaw=null;if(b.faceTarget&&curs.has(b.faceTarget))targetYaw=yawTo(st.pos,curs.get(b.faceTarget).pos,spec.type);else if(b.rotationY!==null)targetYaw=b.rotationY;
        if(targetYaw!==null){actions.push({target:b.target,type:'rotate',start:b.start,end:Math.max(b.start+.01,b.end),from:st.rot,to:targetYaw,reason:b.faceTarget?`face ${b.faceTarget}`:'explicit yaw'});st.rot=targetYaw}
      }else{
        const expressive=['wave','dance','react','jump'].includes(b.action);
        if(expressive&&!interactionFaced&&shot.focus.length===2){
          const [idA,idB]=shot.focus,stA=curs.get(idA),stB=curs.get(idB),spA=plan.assets.find(x=>x.id===idA),spB=plan.assets.find(x=>x.id===idB);
          if(stA&&stB&&spA&&spB){const yawA=yawTo(stA.pos,stB.pos,spA.type),yawB=yawTo(stB.pos,stA.pos,spB.type),turnStart=Math.max(shot.start,b.start-.18);if(yawA!==null){actions.push({target:idA,type:'rotate',start:turnStart,end:b.start,from:stA.rot,to:yawA,reason:`auto-face ${idB}`});stA.rot=yawA}if(yawB!==null){actions.push({target:idB,type:'rotate',start:turnStart,end:b.start,from:stB.rot,to:yawB,reason:`auto-face ${idA}`});stB.rot=yawB}}
          interactionFaced=true;
        }
        actions.push({target:b.target,type:'clip',start:b.start,end:b.end,clip:actionClip(spec.type,b.action)});
      }
    }
  }
  timeline={actions};
}'''+s[end:]
s=s.replace("else if(a.type==='rotate')rot=t>=a.end?a.to:THREE.MathUtils.lerp(a.from,a.to,smooth((t-a.start)/Math.max(.001,a.end-a.start)));", "else if(a.type==='rotate')rot=t>=a.end?a.to:lerpAngle(a.from,a.to,smooth((t-a.start)/Math.max(.001,a.end-a.start)));")
s=s.replace("const DIRECTOR_SYSTEM=`You are SceneForge Animate Director. Return one JSON object only. Use assets robot/fox; beats walk run wave dance react jump idle pause face; cameraPreset wide medium close reaction follow. Produce a readable 3-5 shot animation. Keep continuity and avoid teleporting. Output {assistant_message,title,summary,duration,assets:[{id,label,type,color,position:[x,0,z],rotationY}],shots:[{id,title,caption,start,end,cameraPreset,focus:[ids],beats:[{target,action,start,end,to?,rotationY?}]}]}.`;", "const DIRECTOR_SYSTEM=`You are SceneForge Animate Director. Return one JSON object only. Use assets robot/fox; beats walk run wave dance react jump idle pause face; cameraPreset wide medium close reaction follow. Produce a readable 3-5 shot animation. Keep continuity and avoid teleporting. FACING RULES: the runtime automatically faces walk/run actors toward their movement vector, so do not guess rotationY for locomotion. Before interaction actions such as wave, dance, react or jump, use a face beat with faceTarget set to the other actor when they should look at each other. Prefer faceTarget over numeric rotationY. In two-character interaction shots, make facing intent explicit. Output {assistant_message,title,summary,duration,assets:[{id,label,type,color,position:[x,0,z],rotationY}],shots:[{id,title,caption,start,end,cameraPreset,focus:[ids],beats:[{target,action,start,end,to?,faceTarget?,rotationY?}]}]}.`;")
s=s.replace('function candidateTimes(){', r'''function activeMoveAt(id,t){return timeline.actions.find(a=>a.target===id&&a.type==='move'&&t>=a.start&&t<=a.end)||null}
function orientationDiagnostics(t){const sh=shotAt(t),rows=[];for(const spec of plan.assets){const st=stateAt(spec.id,t),forward=forwardFromYaw(st.rot,spec.type),move=activeMoveAt(spec.id,t);let moveDirection=null,moveFacingDot=null,interactionTarget=null,interactionFacingDot=null;if(move){moveDirection=unit2(move.to[0]-move.from[0],move.to[2]-move.from[2]);moveFacingDot=Number(dot2(forward,moveDirection).toFixed(3))}if(sh?.focus?.length===2&&sh.focus.includes(spec.id)){interactionTarget=sh.focus.find(x=>x!==spec.id)||null;if(interactionTarget){const other=stateAt(interactionTarget,t).pos,dir=unit2(other[0]-st.pos[0],other[2]-st.pos[2]);interactionFacingDot=Number(dot2(forward,dir).toFixed(3))}}rows.push({id:spec.id,label:spec.label,rotationY:Number(st.rot.toFixed(3)),forwardXZ:forward.map(x=>Number(x.toFixed(3))),moveDirectionXZ:moveDirection,moveFacingDot,interactionTarget,interactionFacingDot})}return rows}
function orientationWarnings(diags){const out=[];for(const d of diags){if(d.moveFacingDot!=null&&d.moveFacingDot<0.5)out.push(`${d.id} moving while facing wrong direction (dot=${d.moveFacingDot})`);if(d.interactionFacingDot!=null&&d.interactionFacingDot<0&&d.moveFacingDot==null)out.push(`${d.id} faces away from ${d.interactionTarget} during interaction (dot=${d.interactionFacingDot})`)}return out}
function candidateTimes(){''',1)
s=s.replace("const times=candidateTimes(),frames=[],views=['director','left','right'];", "const times=candidateTimes(),frames=[],views=['director','left','right'];let orientationWarningCount=0;")
s=s.replace("    const sh=shotAt(t);\n    for(const view of views){", "    const sh=shotAt(t),orientation=orientationDiagnostics(t),ow=orientationWarnings(orientation);orientationWarningCount+=ow.length;\n    for(const view of views){")
s=s.replace("const frame={time:t,view,title:sh?.title||'',caption:sh?.caption||'',dataUrl};frames.push(frame);", "const frame={time:t,view,title:sh?.title||'',caption:sh?.caption||'',orientation,warnings:ow,dataUrl};frames.push(frame);")
s=s.replace("ui.sampleInfo.className='validation good';ui.sampleInfo.textContent=`已截取 ${frames.length} 张：${times.length} 个时间点 × 3 视角（director / left / right）。`;", "ui.sampleInfo.className=orientationWarningCount?'validation warn':'validation good';ui.sampleInfo.textContent=`已截取 ${frames.length} 张：${times.length} 个时间点 × 3 视角。程序化朝向 QA 发现 ${orientationWarningCount} 条可疑项。`;")
s=s.replace("const REVIEW_SYSTEM=`You are the visual QA and repair agent for SceneForge Animate. You receive dense time samples of a Three.js animation. Every sample time has three views: director, left, right. Diagnose story readability, actor visibility, framing, overlaps/collisions, continuity, action timing, camera focus, and obvious pose/location mistakes. Use the side views to catch depth overlap that the director view may hide. Return one COMPLETE corrected Director Plan JSON, not a patch. Preserve the user's story and supported schema. Include assistant_message, review_summary and issues, plus title, summary, duration, assets, shots. Output JSON only.`;", "const REVIEW_SYSTEM=`You are the visual QA and repair agent for SceneForge Animate. You receive dense time samples of a Three.js animation. Every sample time has director/left/right images plus structured orientation metadata. FACING IS A FIRST-CLASS QA CHECK. A moving actor should face its movement direction; moveFacingDot below 0.5 is suspicious and below 0 is clearly wrong. In two-character interaction shots (wave, react, dance, conversation-like beats), actors should normally face each other unless the story intentionally says otherwise; a negative interactionFacingDot means the actor is facing away. Check images AND the numeric metadata. Repair facing with face beats using faceTarget rather than guessing numeric rotationY. Also diagnose story readability, actor visibility, framing, overlaps/collisions, continuity, action timing and camera focus. Return one COMPLETE corrected Director Plan JSON, not a patch. Preserve the user's story and supported schema. Include assistant_message, review_summary and issues, plus title, summary, duration, assets, shots. Output JSON only.`;")
s=s.replace("      parts.push({type:'text',text:`t=${f.time.toFixed(2)}s view=${f.view} shot=${f.title} intended=${f.caption}`});", "      const orientationText=f.view==='director'?`\\nOrientation metadata: ${JSON.stringify(f.orientation)}${f.warnings?.length?`\\nOrientation warnings: ${f.warnings.join('; ')}`:''}`:'';\n      parts.push({type:'text',text:`t=${f.time.toFixed(2)}s view=${f.view} shot=${f.title} intended=${f.caption}${orientationText}`});")
s=s.replace("{id:'blue',label:'蓝色机器人',type:'robot',color:'#4da3ff',position:[-4,0,0],rotationY:1.57}", "{id:'blue',label:'蓝色机器人',type:'robot',color:'#4da3ff',position:[-4,0,0],rotationY:-1.57}")
s=s.replace("{id:'purple',label:'紫色机器人',type:'robot',color:'#c879ff',position:[4,0,0],rotationY:-1.57}", "{id:'purple',label:'紫色机器人',type:'robot',color:'#c879ff',position:[4,0,0],rotationY:1.57}")
s=s.replace("beats:[{target:'blue',action:'wave',start:4.5,end:6.5}]", "beats:[{target:'blue',action:'face',start:4.25,end:4.45,faceTarget:'purple'},{target:'purple',action:'face',start:4.25,end:4.45,faceTarget:'blue'},{target:'blue',action:'wave',start:4.5,end:6.5}]")
s=s.replace("beats:[{target:'purple',action:'dance',start:7.4,end:10.1},{target:'blue',action:'react',start:8,end:9.5}]", "beats:[{target:'purple',action:'face',start:7.15,end:7.35,faceTarget:'blue'},{target:'blue',action:'face',start:7.15,end:7.35,faceTarget:'purple'},{target:'purple',action:'dance',start:7.4,end:10.1},{target:'blue',action:'react',start:8,end:9.5}]")
Path('sceneforge-animate/phase14.html').write_text(s,encoding='utf-8')
